# Generated by Django 4.1.7 on 2023-07-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=15, null=True)),
                ('card_number', models.CharField(blank=True, max_length=25, null=True)),
                ('number_of_activations', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('has_requested', models.BooleanField(default=False)),
                ('total_calories', models.IntegerField(default=0)),
                ('total_protein', models.IntegerField(default=0)),
                ('total_fat', models.IntegerField(default=0)),
                ('total_carbs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedUser',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_day', models.DateField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('proteins', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=100)),
                ('пол', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=7)),
                ('цель', models.CharField(choices=[('G', 'Набрать вес'), ('L', 'Сбросить вес')], default='G', max_length=12)),
                ('место', models.CharField(choices=[('H', 'Дом'), ('G', 'Зал')], default='H', max_length=3)),
                ('уровень', models.CharField(choices=[('P', 'Профессиональный'), ('N', 'Новичок')], default='P', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PaidUser',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_day', models.DateField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('proteins', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=100)),
                ('пол', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=7)),
                ('цель', models.CharField(choices=[('G', 'Набрать вес'), ('L', 'Сбросить вес')], default='G', max_length=12)),
                ('место', models.CharField(choices=[('H', 'Дом'), ('G', 'Зал')], default='H', max_length=3)),
                ('уровень', models.CharField(choices=[('P', 'Профессиональный'), ('N', 'Новичок')], default='N', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=3000, null=True)),
                ('answer', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnpaidUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('has_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], max_length=10)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('course_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.courseday')),
            ],
        ),
        migrations.AddField(
            model_name='courseday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.paiduser'),
        ),
    ]
