# Generated by Django 4.1.7 on 2024-03-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unpaiduser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unpaiduser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseday',
            name='total_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='courseday',
            name='total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='courseday',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='courseday',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paiduser',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiduser',
            name='proteins',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiduser',
            name='user',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
